In [ ]:
import pandas as pd

df1 = pd.read_csv('transaction_1_v5.csv')
df2 = pd.read_csv('transaction_2_v5.csv')
df  = pd.concat([df1, df2], ignore_index=True)
df["Date"] = pd.to_datetime(df["DateTime"]).dt.date

In [2]:
df

,Unnamed: 0,TransactionID,DateTime,Date_Key,Branch,Customer_ID,SKU_ID,SKU,Brand,SKU_Category,Qty,NormalPrice,DiscountedPrice,DiscountPercentage,Total_Price,IsPromo,Date
0,0,T194698,2025-09-26 09:17:03,20250926,Surabaya,C59453,S014,Nabati Drinko Richoco 150ml,Richoco,Minuman,2,4000.0,4000.0,0.0,8000.0,0,2025-09-26
1,1,T211333,2025-10-10 10:10:55,20251010,Jakarta,C99629,S012,Nabati Biskuit Rasa Cokelat,Richoco,Biskuit,5,5000.0,5000.0,0.0,25000.0,0,2025-10-10
2,2,T215168,2025-10-13 16:10:53,20251013,Jakarta,C76801,S019,Richeese Siip Jagung Bakar 20g,Richeese,Extruded Snack,4,3000.0,3000.0,0.0,12000.0,0,2025-10-13
3,3,T066771,2025-06-04 19:53:49,20250604,Bandung,C76470,S020,Richeese Mi Instan Goreng,Richeese,Mi Instan,5,3500.0,3500.0,0.0,17500.0,0,2025-06-04
4,4,T074111,2025-06-12 12:45:01,20250612,Jakarta,C17293,S004,Richoco Wafer Cokelat 10g Renceng,Richoco,Wafer,2,10000.0,10000.0,0.0,20000.0,0,2025-06-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205941,102968,T149880,2025-08-19 11:30:19,20250819,Jakarta,C97598,S018,Nextar Pineapple Pie 30g,Nextar,Kue/Pie,4,7000.0,7000.0,0.0,28000.0,0,2025-08-19
205942,102969,T133695,2025-08-05 14:55:29,20250805,Surabaya,C61263,S003,Richeese Wafer Keju 10g Renceng,Richeese,Wafer,4,10000.0,10000.0,0.0,40000.0,0,2025-08-05
205943,102970,T161933,2025-08-29 14:43:40,20250829,Bandung,C09371,S001,Richeese Wafer Keju 50g,Richeese,Wafer,5,5800.0,5220.0,0.1,26100.0,1,2025-08-29
205944,102971,T176868,2025-09-11 09:34:56,20250911,Jakarta,C16465,S019,Richeese Siip Jagung Bakar 20g,Richeese,Extruded Snack,5,3000.0,2100.0,0.3,10500.0,1,2025-09-11
205945,102972,T151959,2025-08-21 19:52:56,20250821,Jakarta,C23272,S008,Richoco Ahh! Extruded 15g,Richoco,Extruded Snack,1,4500.0,4050.0,0.1,4050.0,1,2025-08-21

In [13]:
df.sort_values("TransactionID").head(50)

,Unnamed: 0,TransactionID,DateTime,Date_Key,Branch,Customer_ID,SKU_ID,SKU,Brand,SKU_Category,Qty,NormalPrice,DiscountedPrice,DiscountPercentage,Total_Price,IsPromo,Date
51932,51932,T030001,2025-05-01 13:32:11,20250501,Jakarta,C93017,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
91710,91710,T030002,2025-05-01 09:26:58,20250501,Jakarta,C02748,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
150899,47926,T030003,2025-05-01 11:43:54,20250501,Jakarta,C11395,S001,Richeese Wafer Keju 50g,Richeese,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
109511,6538,T030004,2025-05-01 13:50:06,20250501,Jakarta,C87314,S001,Richeese Wafer Keju 50g,Richeese,Wafer,5,5800.0,5800.0,0.0,29000.0,0,2025-05-01
8886,8886,T030005,2025-05-01 12:24:59,20250501,Jakarta,C23898,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
190315,87342,T030006,2025-05-01 13:01:19,20250501,Jakarta,C48556,S001,Richeese Wafer Keju 50g,Richeese,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
8287,8287,T030007,2025-05-01 16:46:34,20250501,Jakarta,C69480,S001,Richeese Wafer Keju 50g,Richeese,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
141249,38276,T030008,2025-05-01 12:01:05,20250501,Jakarta,C09693,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
126047,23074,T030009,2025-05-01 10:25:43,20250501,Jakarta,C99300,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
162570,59597,T030010,2025-05-01 16:13:22,20250501,Jakarta,C55592,S001,Richeese Wafer Keju 50g,Richeese,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
168417,65444,T030011,2025-05-01 13:15:44,20250501,Jakarta,C86808,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
48164,48164,T030012,2025-05-01 18:24:59,20250501,Jakarta,C38045,S001,Richeese Wafer Keju 50g,Richeese,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
6119,6119,T030013,2025-05-01 09:24:06,20250501,Jakarta,C67564,S001,Richeese Wafer Keju 50g,Richeese,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
156737,53764,T030014,2025-05-01 16:23:10,20250501,Jakarta,C13987,S001,Richeese Wafer Keju 50g,Richeese,Wafer,3,5800.0,5800.0,0.0,17400.0,0,2025-05-01
124947,21974,T030015,2025-05-01 11:32:58,20250501,Jakarta,C64506,S001,Richeese Wafer Keju 50g,Richeese,Wafer,5,5800.0,5800.0,0.0,29000.0,0,2025-05-01
191720,88747,T030016,2025-05-01 17:27:06,20250501,Jakarta,C52257,S001,Richeese Wafer Keju 50g,Richeese,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
179092,76119,T030017,2025-05-01 15:22:23,20250501,Jakarta,C63336,S001,Richeese Wafer Keju 50g,Richeese,Wafer,5,5800.0,5800.0,0.0,29000.0,0,2025-05-01
133880,30907,T030018,2025-05-01 14:26:34,20250501,Jakarta,C08111,S001,Richeese Wafer Keju 50g,Richeese,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
184388,81415,T030019,2025-05-01 11:00:04,20250501,Jakarta,C90983,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
161859,58886,T030020,2025-05-01 19:08:14,20250501,Jakarta,C50637,S001,Richeese Wafer Keju 50g,Richeese,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
49615,49615,T030021,2025-05-01 11:31:38,20250501,Jakarta,C87940,S001,Richeese Wafer Keju 50g,Richeese,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
92828,92828,T030022,2025-05-01 13:22:38,20250501,Jakarta,C33828,S001,Richeese Wafer Keju 50g,Richeese,Wafer,5,5800.0,5800.0,0.0,29000.0,0,2025-05-01
16734,16734,T030023,2025-05-01 15:58:50,20250501,Jakarta,C64045,S001,Richeese Wafer Keju 50g,Richeese,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
79333,79333,T030024,2025-05-01 17:52:05,20250501,Jakarta,C69164,S001,Richeese Wafer Keju 50g,Richeese,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
55063,55063,T030025,2025-05-01 12:29:10,20250501,Jakarta,C21977,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
131789,28816,T030026,2025-05-01 15:32:00,20250501,Jakarta,C06777,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
190096,87123,T030027,2025-05-01 12:12:40,20250501,Jakarta,C21960,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,3,5800.0,5800.0,0.0,17400.0,0,2025-05-01
141261,38288,T030028,2025-05-01 19:08:36,20250501,Jakarta,C66200,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
196848,93875,T030029,2025-05-01 19:53:31,20250501,Jakarta,C51006,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
120493,17520,T030030,2025-05-01 09:57:51,20250501,Jakarta,C89475,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
63744,63744,T030031,2025-05-01 09:36:48,20250501,Jakarta,C94210,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
40069,40069,T030032,2025-05-01 10:27:53,20250501,Jakarta,C55681,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,5,5800.0,5800.0,0.0,29000.0,0,2025-05-01
142493,39520,T030033,2025-05-01 11:01:52,20250501,Jakarta,C26310,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
8579,8579,T030034,2025-05-01 15:03:54,20250501,Jakarta,C12689,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,3,5800.0,5800.0,0.0,17400.0,0,2025-05-01
22474,22474,T030035,2025-05-01 14:23:04,20250501,Jakarta,C89046,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
15587,15587,T030036,2025-05-01 19:47:15,20250501,Jakarta,C86203,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
193368,90395,T030037,2025-05-01 14:15:28,20250501,Jakarta,C56251,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,3,5800.0,5800.0,0.0,17400.0,0,2025-05-01
194842,91869,T030038,2025-05-01 12:18:25,20250501,Jakarta,C11412,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,3,5800.0,5800.0,0.0,17400.0,0,2025-05-01
123204,20231,T030039,2025-05-01 15:51:40,20250501,Jakarta,C88615,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
82147,82147,T030040,2025-05-01 10:39:00,20250501,Jakarta,C39385,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,3,5800.0,5800.0,0.0,17400.0,0,2025-05-01
154056,51083,T030041,2025-05-01 10:22:30,20250501,Jakarta,C46844,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,2,5800.0,5800.0,0.0,11600.0,0,2025-05-01
108744,5771,T030042,2025-05-01 18:47:56,20250501,Jakarta,C02050,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
63700,63700,T030043,2025-05-01 09:47:11,20250501,Jakarta,C61435,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,5,5800.0,5800.0,0.0,29000.0,0,2025-05-01
168396,65423,T030044,2025-05-01 15:08:40,20250501,Jakarta,C51408,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,3,5800.0,5800.0,0.0,17400.0,0,2025-05-01
24241,24241,T030045,2025-05-01 11:19:23,20250501,Jakarta,C12875,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,1,5800.0,5800.0,0.0,5800.0,0,2025-05-01
191070,88097,T030046,2025-05-01 09:07:35,20250501,Jakarta,C02558,S002,Richoco Wafer Cokelat 50g,Richoco,Wafer,4,5800.0,5800.0,0.0,23200.0,0,2025-05-01
173660,70687,T030047,2025-05-01 17:34:24,20250501,Jakarta,C21358,S003,Richeese Wafer Keju 10g Renceng,Richeese,Wafer,5,10000.0,10000.0,0.0,50000.0,0,2025-05-01
158150,55177,T030048,2025-05-01 10:01:53,20250501,Jakarta,C94180,S003,Richeese Wafer Keju 10g Renceng,Richeese,Wafer,3,10000.0,10000.0,0.0,30000.0,0,2025-05-01
93930,93930,T030049,2025-05-01 09:03:32,20250501,Jakarta,C58872,S003,Richeese Wafer Keju 10g Renceng,Richeese,Wafer,5,10000.0,10000.0,0.0,50000.0,0,2025-05-01
22551,22551,T030050,2025-05-01 16:06:02,20250501,Jakarta,C70092,S003,Richeese Wafer Keju 10g Renceng,Richeese,Wafer,1,10000.0,10000.0,0.0,10000.0,0,2025-05-01

In [ ]:
# Gambaran umum
print("Total transaksi:", len(df))
print("Periode:", df["DateTime"].min(), "→", df["DateTime"].max())
print("\nBranch:", df["Branch"].unique())
print("Jumlah branch:", df["Branch"].nunique())

print("\nJumlah SKU:", df["SKU_ID"].nunique())
print("SKU list:\n", df.groupby(["SKU_ID","SKU","Brand","SKU_Category"]).size().reset_index().drop(columns=0))

print("\nCategory:\n", df["SKU_Category"].value_counts())

print("\nTransaksi per branch:\n", df["Branch"].value_counts())

print("\nPromo vs non-promo:\n", df["IsPromo"].value_counts())
print("% promo:", round(df["IsPromo"].mean()*100, 1), "%")

print("\nDiskon yang ada:", sorted(df["DiscountPercentage"].unique()))

Total transaksi: 205946
Periode: 2025-05-01 09:00:14 → 2025-10-30 20:58:13

Branch: ['Surabaya' 'Jakarta' 'Bandung' 'Semarang']
Jumlah branch: 4

Jumlah SKU: 20
SKU list:
    SKU_ID                                SKU     Brand    SKU_Category
0    S001            Richeese Wafer Keju 50g  Richeese           Wafer
1    S002          Richoco Wafer Cokelat 50g   Richoco           Wafer
2    S003    Richeese Wafer Keju 10g Renceng  Richeese           Wafer
3    S004  Richoco Wafer Cokelat 10g Renceng   Richoco           Wafer
4    S005            Nextar Brownies Pie 40g    Nextar         Kue/Pie
5    S006              Nextar Nastar Pie 30g    Nextar         Kue/Pie
6    S007             Richeese Siip Keju 20g  Richeese  Extruded Snack
7    S008          Richoco Ahh! Extruded 15g   Richoco  Extruded Snack
8    S009      Richeese Mi Instan Keju Pedas  Richeese       Mi Instan
9    S010      Richeese Mi Instan Ramen Keju  Richeese       Mi Instan
10   S011         Nabati Biskuit Rasa Kelapa  Richeese         Biskuit
11   S012        Nabati Biskuit Rasa Cokelat   Richoco         Biskuit
12   S013       Nabati Drinko Richeese 150ml  Richeese         Minuman
13   S014        Nabati Drinko Richoco 150ml   Richoco         Minuman
14   S015       Richeese Wafer Pink Lava 50g  Richeese           Wafer
15   S016         Richoco Wafer Hazelnut 50g   Richoco           Wafer
16   S017           Nextar Choco Delight 40g    Nextar         Kue/Pie
17   S018           Nextar Pineapple Pie 30g    Nextar         Kue/Pie
18   S019     Richeese Siip Jagung Bakar 20g  Richeese  Extruded Snack
19   S020          Richeese Mi Instan Goreng  Richeese       Mi Instan

Category:
 SKU_Category
Wafer             62713
Kue/Pie           41797
Mi Instan         31736
Extruded Snack    29973
Biskuit           19931
Minuman           19796
Name: count, dtype: int64

Transaksi per branch:
 Branch
Jakarta     102555
Surabaya     55189
Bandung      29397
Semarang     18805
Name: count, dtype: int64

Promo vs non-promo:
 IsPromo
0    142331
1     63615
Name: count, dtype: int64
% promo: 30.9 %

Diskon yang ada: [0.0, 0.1, 0.2, 0.3, 0.5]

In [7]:
import calendar

# Cek hari terakhir yang ada di data Oktober
oct_data = df[df["Date"].dt.month == 10]
print("Hari Oktober yang ada di data:")
print(sorted(oct_data["Date"].dt.day.unique()))

# Bandingkan dengan jumlah hari seharusnya di Oktober 2025
print("\nOktober 2025 seharusnya punya hari:", calendar.monthrange(2025, 10)[1], "hari")

Hari Oktober yang ada di data:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

Oktober 2025 seharusnya punya hari: 31 hari

In [5]:
df["Date"] = pd.to_datetime(df["Date"])

# Cek jumlah hari unik per bulan
print(df.groupby(df["Date"].dt.month)["Date"].nunique())

# Cek total hari unik tanpa Oktober
df_no_oct = df[df["Date"].dt.month != 10]
print("\nTotal hari tanpa Oktober:", df_no_oct["Date"].nunique())
print("Mei–Sep: 31+30+31+31+30 =", 31+30+31+31+30, "hari")

Date
5     31
6     30
7     31
8     31
9     30
10    30
Name: Date, dtype: int64

Total hari tanpa Oktober: 153
Mei–Sep: 31+30+31+31+30 = 153 hari

In [14]:
# Cek variasi harga per SKU per branch per hari
check = df.groupby(["Date", "Branch", "SKU_ID"])["DiscountPercentage"].nunique()
print("Maksimal variasi discount dalam 1 hari per SKU per branch:")
print(check.max())  # harusnya = 1
print("\nAda ga yang lebih dari 1 diskon dalam 1 hari?")
print((check > 1).sum())

Maksimal variasi discount dalam 1 hari per SKU per branch:
1

Ada ga yang lebih dari 1 diskon dalam 1 hari?
0